### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#115]
It seems that lettuce messes up with two scenarios, it combines them together...

```
Scenario Outline: Install misc packages (with operators)          # home/miki/pyg/tests/features/install.feature:94
  Given I use "standard-2.7" environment                          # home/miki/pyg/tests/features/steps.py:117
  Given I use "tmp_install" temporary folder                      # home/miki/pyg/tests/features/steps.py:90
  When I execute pyg install -U "<pkg>"                           # home/miki/pyg/tests/features/steps.py:165
  Then the return code is 0                                       # home/miki/pyg/tests/features/steps.py:199

Examples:
  | pkg                                                         |
  | bottle==0.9.5                                               |
  | dulwich!=0.7.1                                              |
  | grin<=1.2.1                                                 |
  | buzhug>1.6                                                  |
  | gevent<0.13.6                                               |
  | lk>=1                                                       |
  | Scenario Otline: Install packages from VCS                  |
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 119, in __call__
      ret = self.function(self.step, *args, **kw)
    File "/home/miki/pyg/tests/features/steps.py", line 205, in the_return_code_is
      code, given_code, out_desc))
  AssertionError: Invalid code, got 1, expected 0
  cmd: /tmp/pyg_czJ4or_test_env/standard-2.7/bin/pyg -d install -U "Scenario Otline: Install packages from VCS"
  stdout:

  stderr:

  -EOF-

  | Given I use "standard-2.7" environment                      |
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 119, in __call__
      ret = self.function(self.step, *args, **kw)
    File "/home/miki/pyg/tests/features/steps.py", line 205, in the_return_code_is
      code, given_code, out_desc))
  AssertionError: Invalid code, got 1, expected 0
  cmd: /tmp/pyg_czJ4or_test_env/standard-2.7/bin/pyg -d install -U "Scenario Otline: Install packages from VCS"
  stdout:

  stderr:

  -EOF-

  | Given I use "tmp_install" temporary folder                  |
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 119, in __call__
      ret = self.function(self.step, *args, **kw)
    File "/home/miki/pyg/tests/features/steps.py", line 205, in the_return_code_is
      code, given_code, out_desc))
  AssertionError: Invalid code, got 1, expected 0
  cmd: /tmp/pyg_czJ4or_test_env/standard-2.7/bin/pyg -d install -U "Scenario Otline: Install packages from VCS"
  stdout:

  stderr:

  -EOF-

  | When I execute pyg install <url>                            |
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 119, in __call__
      ret = self.function(self.step, *args, **kw)
    File "/home/miki/pyg/tests/features/steps.py", line 205, in the_return_code_is
      code, given_code, out_desc))
  AssertionError: Invalid code, got 1, expected 0
  cmd: /tmp/pyg_czJ4or_test_env/standard-2.7/bin/pyg -d install -U "When I execute pyg install <url>"
  stdout:

  stderr:

  -EOF-

  | Then the return code is 0                                   |
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 119, in __call__
      ret = self.function(self.step, *args, **kw)
    File "/home/miki/pyg/tests/features/steps.py", line 205, in the_return_code_is
      code, given_code, out_desc))
  AssertionError: Invalid code, got 1, expected 0
  cmd: /tmp/pyg_czJ4or_test_env/standard-2.7/bin/pyg -d install -U "When I execute pyg install <url>"
  stdout:

  stderr:

  -EOF-

  | git+git@github.com:rubik/pkgtools.git#egg=pkgtools          |
  | git+https://github.com/fdev31/zicbee.git#egg=zicbee         |
  | hg+https://rubik@bitbucket.org/neithere/argh#egg=argh       |
  | hg+https://rubik@bitbucket.org/birkenfeld/sphinx#egg=sphinx |
  | bzr+lp:wadllib#egg=wadllib                                  |
```

**Comment by rubik** [comment]
Sorry, it was my fault...
