### ISSUE TITLE
ImportError: cannot import name EggDir

### ISSUE THREAD

**Issue by markon** [rubik/pyg#21]
I've just installed Pyg from source and this is the "pyg" command output:

Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 8, in <module>
    load_entry_point('pyg==0.2', 'console_scripts', 'pyg')()
  File "build/bdist.linux-i686/egg/pyg/**init**.py", line 9, in main
    # See the README file for information on usage and redistribution.
  File "build/bdist.linux-i686/egg/pyg/types.py", line 9, in <module>
    # iterator.  Don't check the type!  Use hasattr to check for both
ImportError: cannot import name EggDir

I've also tried to install it by using easy_install, but it gives another error:

Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 8, in <module>
    load_entry_point('pyg==0.2', 'console_scripts', 'pyg')()
  File "build/bdist.linux-i686/egg/pyg/**init**.py", line 80, in main

  File "build/bdist.linux-i686/egg/pyg/**init**.py", line 13, in _set_up

ImportError: No module named argh

I guess they're not strictly related to pyg, but of course because you let it download an old "pkgtools" version. Please upload the new pkgtools :)

**Comment by rubik** [comment]
Thank you Markon!
For the first one: yes, I have to upload the new version of pkgtools! For the second one: I forgot to add 'argh' to setuptools requirements. I'll fix that now.

**Comment by rubik** [comment]
Fixed in:
https://github.com/rubik/pyg/commit/4c7616c3adf783b107186c7cf9ad59650c4ea118
and previous.

Can you try it now? I tried installing it from source (version 0.3 isn't on PyPI yet) and it worked.
