### ISSUE TITLE
install not working on "lk"

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#63]
Running "pyg install lk" I get that error:

```
OSError: [Errno 20] Not a directory: '/tmp/pyg-0Z7Y67-record/.gitignore'
```

while easy_install works (but not pip, for another reason: error: option --single-version-externally-managed not recognized).

**Comment by rubik** [comment]
Thank you for bring this to our attention! I will fix that as soon as I understand why it does that.

**Comment by rubik** [comment]
With the above commit I fixed (in part) this issue. Now the error is due to `lk`'s `setup.py`: it does not use setuptools!

**Comment by fdev31** [comment]
You can force setuptools or distribute usage imho.
Once I used a thing like "from setuptools import setup; execfile('setup.py')" to do that (and it used to work :))

**Comment by fdev31** [comment]
On latest version (v0.6-38-gd8cc85c):

```
(foobar)fab@fab-1015PN:/tmp% pyg install lk                                                                                             22h45
lk is already installed
(foobar)fab@fab-1015PN:/tmp% pyg install -A lk                                                                                          22h45
lk is already installed, upgrading...
No files to remove found
Looking for lk releases on PyPI
Warning: did not find any files on PyPI
Looking for packages at http://pypi.python.org/simple
Best match: lk==1.0
Downloading lk [100% - 5.6 Kb] 
Running setup.py egg_info for lk
Running setup.py install for lk
Error: setup.py did not install lk
Complete output from command setup.py install:
        usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: -c --help [cmd1 cmd2 ...]
           or: -c --help-commands
           or: -c cmd --help

        error: option --single-version-externally-managed not recognized

Trying another file (if there is one)...
Warning: did not find any files on PyPI
Looking for packages at http://pypi.python.org/simple
Warning: did not find any files on PyPI
Looking for packages at http://pypi.python.org/simple
Warning: did not find any files on PyPI
Looking for packages at http://pypi.python.org/simple
Error: An error occurred during the upgrading: InstallationError()
Restoring uninstalled files...
Traceback (most recent call last):
  File "/tmp/foobar/bin/pyg", line 8, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/home/fab/progs/pyg/pyg/__init__.py", line 26, in main
    parser.dispatch()
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/home/fab/progs/pyg/pyg/parser/parser.py", line 51, in install
    opts.install_func(args)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 112, in install_func
    _install_package_from_name(package)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 73, in _install_package_from_name
    return Installer(package).install()
  File "/home/fab/progs/pyg/pyg/inst.py", line 88, in install
    updater.restore_files(self.req)
  File "/home/fab/progs/pyg/pyg/inst.py", line 337, in restore_files
    package = self.removed[package]
KeyError: 'lk'
```

I don't know if the two errors are linked to the same problem, but I think the error itself shouldn't be accessible directly by some user...
(maybe after 1.0 ?), doing a nice error handling with a --debug mode that disables it can be nice in case of bug.
What do you think about that ? (It depends on the public, but doing an auto-mailing system with the traceback can be cheap in python :P). It's up to your roadmap, I don't know if some public document summarize it...
