### ISSUE TITLE
pyg -d can be ineffective

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#66]
pyg seems to rely on a path to run things or not so the following commands won't do the expected result:

```
% mkdir zicbee
% pyg install -Ad zicbee zicbee 
Installing /tmp/foobar/zicbee
%
```

Using a folder with something else (than the package name) just work correctly.

**Comment by rubik** [comment]
Thank you, I didn't know that!

**Comment by rubik** [comment]
Have you tried adding `-g`? If it works we can add a control to check whether INSTALL_DIR is the same as package name.

**Comment by fdev31** [comment]
With -g, it's installing :) But.....

```
(foobar)fab@fab-1015PN:/tmp% pyg install -Agd zicbee zicbee                                                                             19h31
zicbee is already installed, upgrading...
No files to remove found
Looking for zicbee releases on PyPI
Best match: zicbee==0.9-rc9
Downloading zicbee [100% - 316.8 Kb / 316.8 Kb]              
Checking md5 sum
Running setup.py egg_info for zicbee
Running setup.py install for zicbee
Installing dependencies...
Installing zicbee-mplayer>=0.9 (from zicbee)
        zicbee-mplayer>=0.9 is already installed, upgrading...
        No files to remove found
        Looking for zicbee-mplayer releases on PyPI
        Best match: zicbee-mplayer==0.9.1
        Downloading zicbee-mplayer [100% - 12.0 Kb / 12.0 Kb]             
        Checking md5 sum
        Running setup.py egg_info for zicbee-mplayer
        Running setup.py install for zicbee-mplayer
        zicbee-mplayer installed successfully
Installing zicbee-lib>=0.7.3 (from zicbee)
        zicbee-lib>=0.7.3 is already installed, upgrading...
        No files to remove found
        Looking for zicbee-lib releases on PyPI
        Best match: zicbee-lib==0.7.3
        Downloading zicbee-lib [100% - 22.1 Kb / 22.1 Kb]              
        Checking md5 sum
        Running setup.py egg_info for zicbee-lib
        Running setup.py install for zicbee-lib
        zicbee-lib installed successfully
Installing mutagen>=1.20 (from zicbee)
        mutagen>=1.20 is already installed, upgrading...
        No files to remove found
        Looking for mutagen releases on PyPI
        Warning: did not find any files on PyPI
        Looking for packages at http://pypi.python.org/simple
        Best match: mutagen==1.20
        Downloading mutagen [100% - 636.4 Kb / 636.4 Kb]              
        Running setup.py egg_info for mutagen
        Running setup.py install for mutagen
        mutagen installed successfully
Installing buzhug>=1.8 (from zicbee)
        buzhug>=1.8 is already installed, upgrading...
        No files to remove found
        Looking for buzhug releases on PyPI
        Warning: did not find any files on PyPI
        Looking for packages at http://pypi.python.org/simple
        Warning: did not find any files on PyPI
        Looking for packages at http://pypi.python.org/simple
        Warning: did not find any files on PyPI
        Looking for packages at http://pypi.python.org/simple
        Warning: did not find any files on PyPI
        Looking for packages at http://pypi.python.org/simple
        Error: An error occurred during the upgrading: InstallationError()
        Restoring uninstalled files...
Traceback (most recent call last):
  File "/tmp/foobar/bin/pyg", line 8, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/home/fab/progs/pyg/pyg/__init__.py", line 26, in main
    parser.dispatch()
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/home/fab/progs/pyg/pyg/parser/parser.py", line 51, in install
    opts.install_func(args)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 112, in install_func
    _install_package_from_name(package)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 73, in _install_package_from_name
    return Installer(package).install()
  File "/home/fab/progs/pyg/pyg/inst.py", line 93, in install
    Installer._install_deps(r.reqset, r.name)
  File "/home/fab/progs/pyg/pyg/inst.py", line 63, in _install_deps
    Installer(req).install()
  File "/home/fab/progs/pyg/pyg/inst.py", line 88, in install
    updater.restore_files(self.req)
  File "/home/fab/progs/pyg/pyg/inst.py", line 337, in restore_files
    package = self.removed['package']
KeyError: 'package'
(foobar)fab@fab-1015PN:/tmp%                                                                                                            19h32

```

 Also, as a minor improvement, where you fail because some folder is not created (like install -d) we could automatically create the folder... (and fail correctly if something is wrong).

**Comment by rubik** [comment]
Oh no!! I'm stupid. In inst.py I wrote 'package' instead of package:
https://github.com/rubik/pyg/blob/master/pyg/inst.py#L337

Now I cannot fix, because I'm on another computer (it's not mine).

**Comment by rubik** [comment]
The problem is here:
https://github.com/rubik/pyg/blob/master/pyg/core.py#L225

```
if args_manager['install']['install_dir'] != INSTALL_DIR:
        dir = args_manager['install']['install_dir']
        args += ['--root', dir]
```

I tried other configurations with `--home` or `--install-base` but nothing worked...

**Comment by rubik** [comment]
With this commit it should work, but it doesn't. If you analyze the output, you can see that files are copied in the right directory:

```
miki@miki-laptop:~/pyg$ pyg install iterutils -d test
Looking for iterutils releases on PyPI
Best match: iterutils==0.1.6
Downloading iterutils [100% - 2.9 Kb] 
Checking md5 sum
Running setup.py egg_info for iterutils
Running setup.py install for iterutils
running install
running build
running build_py
creating build
creating build/lib.linux-i686-2.7
copying iterutils.py -> build/lib.linux-i686-2.7
running install_lib
creating test
copying build/lib.linux-i686-2.7/iterutils.py -> test
byte-compiling test/iterutils.py to iterutils.pyc
running install_egg_info
running egg_info
creating iterutils.egg-info
writing iterutils.egg-info/PKG-INFO
writing top-level names to iterutils.egg-info/top_level.txt
writing dependency_links to iterutils.egg-info/dependency_links.txt
writing manifest file 'iterutils.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'iterutils.egg-info/SOURCES.txt'
writing manifest file 'iterutils.egg-info/SOURCES.txt'
Copying iterutils.egg-info to test/iterutils-0.1.6-py2.7.egg-info
running install_scripts
writing list of installed files to '/tmp/tmpfiF5F7/.pyg-install-record'

iterutils installed successfully
```

But these lines in particular:

```
byte-compiling test/iterutils.py to iterutils.pyc
Copying iterutils.egg-info to test/iterutils-0.1.6-py2.7.egg-info
```

show that the package is being installed under `test/`. But then, after the installation process, the `test` directory is empty! Why?

**Comment by fdev31** [comment]
Hehe, did you try printing the environement first ? (and maybe the current working directory...)

**Comment by rubik** [comment]
Yeah! Finally I did it! Setuptools wanted the `PYTHONPATH` env var set. So I set it! xD
I fixed the first issue too (install dir with the same name as the package). I commit now.
