### ISSUE TITLE
pyg can't install itself from sources

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#67]
See the following sequence, applied on latest pyg:master installed via python setup.py develop:

```
fab@fab-1015PN:~/progs/pyg% pyg install -e .                                                                                             
Pyg cannot create new files in the installation directory.
Installation directory was:

    /usr/local/lib/python2.7/dist-packages

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

If you need further information about Pyg command-line options visit:

    http://pyg.readthedocs.org/en/latest/cmdline.html
or
    http://pyg-installer.co.nr
##############################################################################################
fab@fab-1015PN:~/progs/pyg% pyg install -e . -d /tmp/something                                                                           
Error: installation directory /tmp/something does not exist
fab@fab-1015PN:~/progs/pyg% mkdir /tmp/something                                                                                         
fab@fab-1015PN:~/progs/pyg% pyg install -e . -d /tmp/something                                                                           
Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 9, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/home/fab/progs/pyg/pyg/__init__.py", line 26, in main
    parser.dispatch()
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/home/fab/progs/pyg/pyg/parser/parser.py", line 51, in install
    opts.install_func(args)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 98, in install_func
    return vcs(args.packname).develop()
  File "/home/fab/progs/pyg/pyg/vcs/__init__.py", line 9, in vcs
    if url.startswith(scheme):
AttributeError: 'list' object has no attribute 'startswith'

##############################################################################################
fab@fab-1015PN:~/progs/pyg% sudo pyg install -u .                                                                                        
Installing /home/fab/progs/pyg
Installing pyg
Running setup.py egg_info for pyg
Running setup.py install for pyg
Installing dependencies...
        argh is already installed
        setuptools is already installed
        pkgtools is already installed
Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 9, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/home/fab/progs/pyg/pyg/__init__.py", line 26, in main
    parser.dispatch()
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/home/fab/progs/pyg/pyg/parser/parser.py", line 51, in install
    opts.install_func(args)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 106, in install_func
    _install_package_from_name(package)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 66, in _install_package_from_name
    return Installer.from_dir(path)
  File "/home/fab/progs/pyg/pyg/inst.py", line 163, in from_dir
    Installer._install_deps(reqset)
  File "/home/fab/progs/pyg/pyg/inst.py", line 70, in _install_deps
    logger.info('Finished installing dependencies for {0.name}=={0.version}', rs.comes_from)
  File "/home/fab/progs/pyg/pyg/log.py", line 37, in info
    self.log(self.INFO, msg, *a, **kw)
  File "/home/fab/progs/pyg/pyg/log.py", line 76, in log
    msg = ' ' * self.indent + msg.format(*a)
AttributeError: 'str' object has no attribute 'name'
##############################################################################################
fab@fab-1015PN:~/progs/pyg% sudo pyg install -e .                                                                                        20h12
Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 9, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/home/fab/progs/pyg/pyg/__init__.py", line 26, in main
    parser.dispatch()
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/usr/local/lib/python2.7/dist-packages/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/home/fab/progs/pyg/pyg/parser/parser.py", line 51, in install
    opts.install_func(args)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 98, in install_func
    return vcs(args.packname).develop()
  File "/home/fab/progs/pyg/pyg/vcs/__init__.py", line 9, in vcs
    if url.startswith(scheme):
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by fdev31** [comment]
Sorry, I misunderstood some usage... I think one of the errors is just a lack of appropriate error message...
"pyg install -Ad ." works, unlike "pyg install -Au ." .
See my last two commits , it fixed some of my installation problems ...

Btw, I just figured out installing "in place" is not supported, is it something that could be planned ? maybe with some help I could implement it myself...

**Comment by rubik** [comment]
The -e option requires an URL, like this:

```
$ pyg install -e git+git@github.com:/rubik/pyg#egg=pyg
```

(Note: this will install that package in development mode, if you want to install it normally just do pyg install git+git@github.com:/rubik/pyg#egg=pyg  this is like Pip).

What do you mean with /installation in place/ ?

**Comment by fdev31** [comment]
Yes, I just figured it out :)

Installating "in place" means "local" for me, it's the "python setup.py develop" mode, so sources are kept in the current folder and it's just updating pth files to point it... I always use it on projects I work so I can change sources and instantly get the changes applied into my system...

**Comment by rubik** [comment]
Ok, I think we should add this feature... But it is a bit complicated.

**Comment by rubik** [comment]
So, can I close this issue and open another for `develop`?

**Comment by fdev31** [comment]
I think so, I didn't experience any problem recently...
About the pyg -e <some folder> which is complicated to achieve, why just not calling python setup.py develop automatically in that folder ? :)

**Comment by rubik** [comment]
Pyg already does that. See:
https://github.com/rubik/pyg/blob/master/pyg/vcs/base.py#L83

**Comment by fdev31** [comment]
But see:

```
fab@fab-1015PN:~/progs/pyg% pyg install -ue .                                                                                           18h21
Error: URL should start with one of these schemes:
('git+', 'hg+', 'bzr+', 'svn+')
```

Tell me if I'm wrong, but -e only works for remote repositories, while it tries to:
- get a copy of the code in current folder
- run "python setup.py develop"

In case the argument is a folder, we just need to jump to last step... I'll have to look longer to the code to understand the limitation but from high-level it's not sounding very complex (just a matter of separating the two steps maybe ?).

**Comment by rubik** [comment]
Yeah you are perfectly right! We can do that rather easily. Let me have a look to the code.

**Comment by rubik** [comment]
See #68
