### ISSUE TITLE
VCS install does not work

### ISSUE THREAD

**Issue by rubik** [rubik/pyg#74]
Suddenly it stopped working!!! Why??
Try it on:

```
$ pyg install git+https://github.com/rubik/pkgtools#egg=pkgtools
Copying data from https://github.com/rubik/pkgtools to /tmp/pyg-Cm1Ky2-record
Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 9, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/home/miki/pyg/pyg/__init__.py", line 26, in main
    parser.dispatch()
  File "/usr/local/lib/python2.7/dist-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/usr/local/lib/python2.7/dist-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/usr/local/lib/python2.7/dist-packages/argh-0.14.0-py2.7.egg/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/home/miki/pyg/pyg/parser/parser.py", line 57, in install
    opts.install_func(args)
  File "/home/miki/pyg/pyg/parser/_opts.py", line 115, in install_func
    _install_package_from_name(package)
  File "/home/miki/pyg/pyg/parser/_opts.py", line 72, in _install_package_from_name
    return vcs(package, tempdir).install()
  File "/home/miki/pyg/pyg/vcs/base.py", line 98, in install
    self.retrieve_data()
  File "/home/miki/pyg/pyg/vcs/base.py", line 47, in retrieve_data
    self.call_cmd([self.url])
  File "/home/miki/pyg/pyg/vcs/base.py", line 80, in call_cmd
    code, output = call_subprocess([self.cmd, self.method] + args, True)
  File "/home/miki/pyg/pyg/utils.py", line 102, in call_subprocess
    output = check_output(args, stderr=subprocess.STDOUT, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 530, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 672, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1213, in _execute_child
    raise child_exception
TypeError: coercing to Unicode: need string or buffer, bool found
```

It seems a subprocess problem...

**Comment by fdev31** [comment]
Here I have a different problem:

```

fab@fab-1015PN:/tmp% sudo pyg install git+https://github.com/rubik/pkgtools#egg=pkgtools          20h36
[sudo] password for fab: 
Copying data from https://github.com/rubik/pkgtools to /tmp/pyg-AcB_8W-record
Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 8, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/home/fab/progs/pyg/pyg/__init__.py", line 26, in main
    parser.dispatch()
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/home/fab/.local/lib/python2.6/site-packages/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/home/fab/progs/pyg/pyg/parser/parser.py", line 57, in install
    opts.install_func(args)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 115, in install_func
    _install_package_from_name(package)
  File "/home/fab/progs/pyg/pyg/parser/_opts.py", line 72, in _install_package_from_name
    return vcs(package, tempdir).install()
  File "/home/fab/progs/pyg/pyg/vcs/base.py", line 58, in install
    Installer.from_dir(self.dir, self.package_name)
  File "/home/fab/progs/pyg/pyg/vcs/base.py", line 35, in dir
    return os.path.join(self.dest, os.listdir(self.dest)[0])
IndexError: list index out of range
```

The destination directory is empty at this point, don't know if it's a workflow problem or if it's just a matter of catching IndexError (only OSError is catched now)

**Comment by rubik** [comment]
Yes, now I have the same problem. But I don't know why the destination directory is empty...
