### ISSUE TITLE
Pyg broken after an upgrade

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#86]
After a recent upgrade I get this error, not sure it's dependent on the system because it happened on two of my machines

```
Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 8, in <module>
    load_entry_point('pyg==0.6', 'console_scripts', 'pyg')()
  File "/usr/local/lib/python2.7/dist-packages/pyg-0.6-py2.7.egg/pyg/__init__.py", line 14, in main
    from pyg.parser.parser import init_parser, load_options
ImportError: No module named parser.parser
```

**Comment by fdev31** [comment]
Ooops! Forget about it, sale .pyc files problem...

**Comment by rubik** [comment]
Good! ;)
