### ISSUE TITLE
Cannot install egg in windows virtualenv py2.7

### ISSUE THREAD

**Issue by scaradim** [rubik/pyg#99]
Microsoft Windows XP [Version 5.1.2600](C) Copyright 1985-2001 Microsoft Corp.

c:_work\home>virtualenv --distribute --no-site-packages --python=c:\python27\python.exe c:\pyve\27\test-lxml
Running virtualenv with interpreter c:\python27\python.exe
New python executable in c:\pyve\27\test-lxml\Scripts\python.exe
Installing distribute........................................................................................................................................................................................done.
Installing pip.................done.

c:_work\home>c:\pyve\27\test-lxml\Scripts\activate.bat

[...]

(test-lxml) c:_work\home>pip install pyg
Requirement already satisfied (use --upgrade to upgrade): pyg in c:\pyve\27\test-lxml\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): distribute in c:\pyve\27\test-lxml\lib\site-packages\distribute-0.6.15-py2.7.egg (from pyg)
Requirement already satisfied (use --upgrade to upgrade): pkgtools>=0.6.2 in c:\pyve\27\test-lxml\lib\site-packages (from pyg)
Requirement already satisfied (use --upgrade to upgrade): argh in c:\pyve\27\test-lxml\lib\site-packages (from pyg)
Cleaning up...

(test-lxml) c:_work\home>python --version
Python 2.7.1

(test-lxml) c:_work\home>pyg install C:\Temp\lxml-2.3-py2.7-win32.egg
Installing C:\Temp\lxml-2.3-py2.7-win32.egg
Installing lxml egg file
Unknown error occurred: unpack requires a string argument of length 46

(test-lxml) c:_work\home>

**Comment by rubik** [comment]
Thank you! :)
At the moment Pyg is untested on Windows, since we don't have a Windows maintainer... As for the error, can you re-run pyg install with the -d flag? (pyg -d install ...)

**Comment by scaradim** [comment]
(test-lxml) c:_work\home>pyg install -d C:\Temp\lxml-2.3-py2.7-win32.egg
Pyg cannot create new files in the installation directory.
Installation directory was:

```
C:\Temp\lxml-2.3-py2.7-win32.egg
```

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

If you need further information about Pyg command-line options visit:

```
http://pyg.readthedocs.org/en/latest/cmdline.html
```

or
    http://pyg-installer.co.nr

(test-lxml) c:_work\home>pyg install C:\Temp\lxml-2.3-py2.7-win32.egg
Installing C:\Temp\lxml-2.3-py2.7-win32.egg
Installing lxml egg file
Unknown error occurred: unpack requires a string argument of length 46

(test-lxml) c:_work\home>

**Comment by rubik** [comment]
Sorry, but I meant to add the `-d` flag _before_ the install command:

```
pyg -d install ...
```

But why have you closed the issue?

**Comment by scaradim** [comment]
The issues is still open. I'm discovering the github site. Probably I've considered nice the blue of close issue button when hovering over it. :)
Here is the right log (BTW this position dependent meaning is quite ambiguous). As debug mode should be less used you could use a --debug for it.

```
Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

c:\_work\home>c:\pyve\27\test-lxml\Scripts\activate.bat
(test-lxml) c:\_work\home>pyg -d install C:\Temp\lxml-2.3-py2.7-win32.egg
Installing C:\Temp\lxml-2.3-py2.7-win32.egg
Installing lxml egg file
Traceback (most recent call last):
  File "c:\pyve\27\test-lxml\Scripts\pyg-script.py", line 9, in <module>
    load_entry_point('pyg==0.7', 'console_scripts', 'pyg')()
  File "c:\pyve\27\test-lxml\lib\site-packages\pyg\__init__.py", line 28, in main
    parser.dispatch()
  File "c:\pyve\27\test-lxml\lib\site-packages\argh\helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "c:\pyve\27\test-lxml\lib\site-packages\argh\helpers.py", line 205, in dispatch
    for line in lines:
  File "c:\pyve\27\test-lxml\lib\site-packages\argh\helpers.py", line 281, in _execute_command
    for line in result:
  File "c:\pyve\27\test-lxml\lib\site-packages\argh\helpers.py", line 264, in _call
    result = args.function(args)
  File "c:\pyve\27\test-lxml\lib\site-packages\pyg\parser\parser.py", line 96, in install
    args_manager['install']['ignore'])
  File "c:\pyve\27\test-lxml\lib\site-packages\pyg\parser\_opts.py", line 94, in install_func
    _install_package_from_name(package, ignore)
  File "c:\pyve\27\test-lxml\lib\site-packages\pyg\parser\_opts.py", line 61, in _install_package_from_name
    return Installer.from_file(path)
  File "c:\pyve\27\test-lxml\lib\site-packages\pyg\inst.py", line 173, in from_file
    installer.install()
  File "c:\pyve\27\test-lxml\lib\site-packages\pyg\core.py", line 155, in install
    with ZipFile(self.fobj) as z:
  File "c:\python27\Lib\zipfile.py", line 712, in __init__
    self._GetContents()
  File "c:\python27\Lib\zipfile.py", line 746, in _GetContents
    self._RealGetContents()
  File "c:\python27\Lib\zipfile.py", line 787, in _RealGetContents
    centdir = struct.unpack(structCentralDir, centdir)
struct.error: unpack requires a string argument of length 46


(test-lxml) c:\_work\home>
```

**Comment by rubik** [comment]
Uhm I don't know... It seems to be a zipfile issue. I'll inquire about it! :)

**Comment by fdev31** [comment]
thanks for testing :-) 

could you manage finding some windows developer able to fix that? if not, we will do a windows bug fixing session later in time, with a low priority. until now, windows version is not bug free :-(
